#!/bin/bash
# URL of the file to download
url="https://raw.githubusercontent.com/Renji-XD/texthooker-ui/main/docs/index.html"

# Destination path and filename for the downloaded file
destination="/home/kaze/jap/texthooker/index.html"

# Use curl to download the file
curl -L "$url" -o "$destination"
